const experience = [
  {
    title: "Founding Engineer",
    company: "Continuum",
    website: "https://www.joincontinuum.com",
    start: "May 2021",
    end: "November 2024",
    stack: [
      "Docker",
      "Github Actions",
      "Python",
      "styled-components",
      "Storybook",
      "Next.js",
      "React.js",
      "TypeScript",
    ],
  },
  {
    title: "Staff Software Engineer",
    company: "Chegg",
    website: "https://www.chegg.com",
    start: "October 2018",
    end: "April 2021",
    stack: [
      "Docker",
      "PHP",
      "Gitlab",
      "styled-components",
      "Next.js",
      "React.js",
      "TypeScript",
    ],
  },
  {
    title: "Lead Software Developer, Web",
    company: "Firefly",
    website: "https://fireflyon.com",
    start: "March 2018",
    end: "July 2018",
    stack: [
      "CircleCI",
      "Python",
      "REST",
      "Node.js",
      "CSS-in-JS",
      "React.js",
      "JavaScript",
    ],
  },
  {
    title: "Chief Technology Officer",
    company: "Synocate",
    website: "https://synocate.com",
    start: "September 2015",
    end: "February 2018",
    stack: [
      "CircleCI",
      "PostgreSQL",
      "REST",
      "Express",
      "Node.js",
      "SCSS",
      "React.js",
      "JavaScript",
    ],
  },
  {
    title: "Software Dev, Website Builder",
    company: "GoDaddy",
    website: "https://www.godaddy.com/websites/website-builder",
    start: "July 2014",
    end: "March 2016",
    stack: [
      "Ruby",
      "SQL",
      ".NET",
      "C#",
      "CSS",
      "Node.js",
      "React.js",
      "JavaScript",
    ],
  },
];

export default experience;
